name: Verify layouts
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  verify-layouts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Verify test standard layout
        run: |
          go run main.go -l layouts/layout.yml -a test-data
      - name: Verify test NPM layout
        run: |
          go run main.go -l layouts/layout-npm.yml -a test-data-npm --substitute-parameters parameters/npm-sigstore.json
