name: Record change to non-main branch
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  create-rsl-entry:
    if: github.repository == 'in-toto/attestation-verifier'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@f31e69c7c18c7473cbce18ed69a559b945d3a738
      - name: Install gitsign
        uses: chainguard-dev/actions/setup-gitsign@main
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Update RSL
        run: |
          git fetch origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log
          gittuf rsl record ${{ github.ref }}
          git push origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log
