name: Record change to main branch
on:
  push:
    branches:
      - 'main'
jobs:
  create-rsl-entry:
    if: github.repository == 'in-toto/attestation-verifier'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@5c0fb4a2a0dc9434598cf2e74bb601d76861fc97
      - name: Install gitsign
        uses: chainguard-dev/actions/setup-gitsign@main
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0
      - name: Update RSL
        env:
          KEY: ${{ secrets.KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gittuf_key_path="/tmp/gittuf-key"
          echo "$KEY" > $gittuf_key_path
          chmod 600 $gittuf_key_path # ssh-keygen signer requires this

          git fetch origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log refs/gittuf/attestations:refs/gittuf/attestations
          GITTUF_DEV=1 gittuf dev attest-github --signing-key $gittuf_key_path --repository ${{ github.repository }} --commit ${{ github.sha }} --base-branch "main"
          gittuf rsl record main
          git push origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log refs/gittuf/attestations:refs/gittuf/attestations
