name: gittuf Verification
on:
  workflow_run:
    workflows: ["Record change to main branch"]
    branches: [main]
    types:
      - completed
jobs:
  gittuf-verify:
    if: github.repository == 'in-toto/attestation-verifier'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@f6589511b7fb806ce365de81caa949b5c468089a
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd attestation-verifier
          gittuf verify-ref main --verbose
